spring.application.name=tareas_gestor

spring.datasource.url=jdbc:mysql://localhost:3306/gestor_tareas_db
spring.datasource.username=root
spring.datasource.password=12345678910
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver 
spring.jpa.show-sql=true
